services:
  kiwi-bot:
    build: https://github.com/TheOksigen/kiwi.git
    restart: unless-stopped
    environment:
      - BOT_TOKEN=BURAYA_BOT_TOKEN_YAZ
      - NODE_ENV=production
    volumes:
      - kiwi-temp:/app/temp

volumes:
  kiwi-temp:
