services:
  kiwi-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - kiwi-temp:/app/temp
      # cookies.txt faylı varsa avtomatik mount olunur
      - ./cookies.txt:/app/cookies.txt:ro
    environment:
      - NODE_ENV=production
      - COOKIES_FILE=/app/cookies.txt

volumes:
  kiwi-temp:
